---
title: "ccbr1016_IPA_upstreamAnalysis"
author: "Da"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(DT)
library(reshape2)
library(ggplot2)
theme_set(theme_classic())
setwd("~/Desktop/active_projects/ccbr1016-RNAseq/analysis/")
```


```{r}
upstream = read.csv("processedData/IPA_Upstream_Analysis_SCR_0.5mM_GCN1SH1_0.5mM.csv", header = T)
upstream$log10P = -log10(upstream$p.value.of.overlap)
upstream$sign.value = sign(upstream$Activation.z.score) * upstream$log10P
```


```{r}
Transcription_Regulators = c("ATF4", "NFKB1", "JUN","CREB1","CTNNB1","MYC")
upstream_TR = upstream[which(upstream$Molecule.Type=="transcription regulator"&upstream$Upstream.Regulator%in%Transcription_Regulators),]

Enzymes = c("KRAS","NRAS","HRAS","ALDH2","OGA","CD38")
upstream_enzyme = upstream[which(upstream$Molecule.Type=="enzyme"&upstream$Upstream.Regulator%in%Enzymes),]

Phosphatases = c("PTEN", "DUSP1","PPP1R15B","PTPN3","DUSP5","PPP5C")
upstream_phosphatase = upstream[which(upstream$Molecule.Type=="phosphatase"&upstream$Upstream.Regulator%in%Phosphatases),]

main = rbind(upstream_TR, upstream_enzyme, upstream_phosphatase)
main = select(main, c("Upstream.Regulator", "Molecule.Type", "Activation.z.score", "log10P"))

main_long = melt(main)
main_long1 = main_long[which(main_long$variable=="Activation.z.score"),]
colnames(main_long1)[4] = "Activation.z.score"
main_long1 = main_long1[,c(1,2,4)]
main_long2 = main_long[which(main_long$variable=="log10P"),]
colnames(main_long2)[4] = "log10P"
main_long2 = main_long2[,c(1,4)]
main_long3 = merge(main_long1, main_long2, by="Upstream.Regulator")
main_long3$sign.value = sign(main_long3$Activation.z.score) * main_long3$log10P

```


```{r}


ggplot(main_long3) +
  geom_point(aes(x = reorder(Upstream.Regulator, abs(sign.value)), y = sign.value),colour="darkgrey") + coord_flip() +
  geom_bar(aes(x = Upstream.Regulator, y = Activation.z.score, fill=Molecule.Type), stat = "identity", position = "dodge") +
  scale_y_continuous(sec.axis = sec_axis(~./1, name = "Activation.z.score")) + facet_wrap(vars(Molecule.Type))+ theme(legend.position = "none")
# +
#   geom_point(aes(x = reorder(Upstream.Regulator, log10P), y = log10P)) +
#   scale_y_continuous(sec.axis = sec_axis(~./1, name = "log10P")) + coord_flip() + facet_wrap(vars(Molecule.Type))+ theme(legend.position = c(0.2, 0.2))

scl = 2
p = 
ggplot(main_long3, aes(fill=Molecule.Type)) +
  geom_bar(aes(x = reorder(Upstream.Regulator, abs(sign.value)), y = sign.value), stat = "identity", position = "dodge") +  coord_flip() + scale_fill_grey()+
  geom_point(aes(x = Upstream.Regulator, y = Activation.z.score*scl),colour="red") +
  scale_y_continuous(sec.axis = sec_axis(~./scl, name = "Activation.z.score")) + facet_wrap(vars(Molecule.Type))+ theme(legend.position = "none",axis.title.x = element_text(size=13, face="bold", colour = "black"),    
    axis.title.y = element_text(size=13, face="bold", colour = "black"),    
    axis.text.x = element_text(size=10, face="bold", colour = "black"), 
    # axis.text.y = element_text(size=12,  colour = "black"), # unbold
    axis.text.y = element_text(size=10, face="bold", colour = "black"),strip.text = element_text(face="bold", size=12), axis.line.x.top = element_line(color = "red"), axis.title.x.top = element_text(color = "red"), axis.text.x.top = element_text(color = "red")) +ylab("sign value (-log10P * sign of activation)") + xlab("Upstream Regulator")+ geom_hline(yintercept = 0, linetype="dotted", 
                color = "darkgrey", size=1)

ggsave(filename = "results/IPA_upstream_main.pdf", plot = p)

```


```{r}
table(upstream$Molecule.Type)

```

```{r}
types = c("kinase","cytokine","growth factor","ligand-dependent nuclear receptor","transmembrane receptor")
myList = list()
for (i in types){
  myList[[i]] = upstream[which(upstream$Molecule.Type==i),]
  myList[[i]] = top_n(x = myList[[i]], n = 5, wt = -p.value.of.overlap)
}

my_data = do.call(dplyr::bind_rows, myList)
my_data = select(my_data, c("Upstream.Regulator", "Molecule.Type", "Activation.z.score", "sign.value"))


ggplot(my_data, aes(fill=Molecule.Type)) +
  geom_bar(aes(x = reorder(Upstream.Regulator, abs(sign.value)), y = sign.value), stat = "identity", position = "dodge") +  coord_flip() + scale_fill_grey()+
  geom_point(aes(x = Upstream.Regulator, y = Activation.z.score*scl),colour="red") +
  scale_y_continuous(sec.axis = sec_axis(~./scl, name = "Activation.z.score")) + facet_wrap(vars(Molecule.Type))+ theme(legend.position = "none",axis.title.x = element_text(size=13, face="bold", colour = "black"),    
    axis.title.y = element_text(size=13, face="bold", colour = "black"),    
    axis.text.x = element_text(size=7, face="bold", colour = "black"), 
    # axis.text.y = element_text(size=12,  colour = "black"), # unbold
    axis.text.y = element_text(size=7, face="bold", colour = "black"),strip.text = element_text(face="bold", size=8), axis.line.x.top = element_line(color = "red"), axis.title.x.top = element_text(color = "red"), axis.text.x.top = element_text(color = "red")) +ylab("sign value (-log10P * sign of activation)") + xlab("Upstream Regulator")+ geom_hline(yintercept = 0, linetype="dotted", 
                color = "darkgrey", size=1) 

# +
# geom_text(aes(x = reorder(Upstream.Regulator, abs(sign.value)), y = sign.value, label=Upstream.Regulator), position=position_dodge(width=0.9), hjust=-0.25)

ggsave(filename = "results/IPA_upstream_supplementary.pdf", plot = p2)


```

```{r}

```

